format = """
$os\
$directory\
$git_branch\
$git_status\
$fill\
$status\
$cmd_duration\
$jobs\
$python\
$nodejs\
$ruby\
$golang\
$rust\
$time\
$line_break\
$character"""

add_newline = false

[os]
disabled = false
style = "bold red"

[fill]
symbol = " "

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"
format = "[$path]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold green"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
stashed = "*"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[status]
disabled = false
format = '[$symbol$status]($style) '
symbol = "✘"

[cmd_duration]
min_time = 3000
format = "took [$duration]($style) "
style = "yellow"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[time]
disabled = false
format = '[$time]($style) '
style = "bold bright-blue"
time_format = "%H:%M:%S"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bold bright-blue"
symbol = " "

[nodejs]
format = '[${symbol}($version )]($style)'
style = "bold green"
symbol = " "

[ruby]
format = '[${symbol}($version )]($style)'
style = "bold red"
symbol = " "

[golang]
format = '[${symbol}($version )]($style)'
style = "bold bright-blue"
symbol = " "

[rust]
format = '[${symbol}($version )]($style)'
style = "bold bright-blue"
symbol = " "
