[[entries]]
default = true
name = "Brave"
url = "https://search.brave.com/search?q=%TERM%"

[[entries]]
name = "Github"
url = "https://github.com/search?q=%TERM%"

[[entries]]
name = "Flathub"
url = "https://flathub.org/apps/search?q=%TERM%"
prefix = "fh"

[[entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"
