#!/usr/bin/env bash

[[ ! -f $HOME/.dotfiles/sessionizer-additions.sh ]] || source $HOME/.dotfiles/sessionizer-additions.sh

if [[ $# -eq 1 ]]; then
  selected=$1
else
  # export TMUX_PATHS="$HOME\n$HOME/.config\n$HOME/.local/share/applications\n$HOME/Documents"
	find_paths=$TMUX_PATHS
	find_depth_paths="$HOME/repos $HOME/repos/code $TMUX_FIND_PATHS"
	folders="$HOME/.dotfiles\n$find_paths\n$(find $find_depth_paths -mindepth 1 -maxdepth 1 -type d 2>/dev/null)"
  if [ -f "/etc/debian_version" ]; then
    selected=$(echo -e "$folders" | fzf --preview="[[ -d {} ]] && (tmux ls | grep \$(basename {}); ls -1ah --color {})")
  else
    selected=$(echo -e "$folders" | fzf --preview="[[ -d {} ]] && (tmux ls | grep \$(basename {}); eza -hla --color=always --icons --git-repos {})")
  fi
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

# tmux switch-client -t $selected_name
if [[ -z $TMUX ]]; then
  tmux attach-session -t $selected_name
else
  tmux switch-client -t $selected_name
fi
